name: SSoT Task
description: SSoT-side task. Doing is managed in vrmmo-novel; do not use status:doing here.
title: "SSOT: "
labels: ["area:ssot","kind:task","status:backlog"]
body:
  - type: textarea
    id: intent
    attributes:
      label: Intent
      description: What to change in SSoT repo
    validations:
      required: true
  - type: textarea
    id: success
    attributes:
      label: Success
      description: Observable completion criteria
    validations:
      required: true
  - type: textarea
    id: non_goals
    attributes:
      label: Non-goals
    validations:
      required: true
  - type: textarea
    id: link_to_novel_doing
    attributes:
      label: Link to novel doing issue (required when work starts)
      description: Paste the novel issue URL labeled status:doing that authorizes this work
    validations:
      required: false
  - type: input
    id: novel_doing
    attributes:
      label: novel_doing (required for status:next)
      description: Paste the URL of the current doing issue in vrmmo-novel (label status:doing must be exactly 1 open).
      placeholder: https://github.com/lencon14/vrmmo-novel/issues/123
    validations:
      required: false
